### ISSUE TITLE
Failed to obtain data for USER despite USER owning minecraft

### ISSUE THREAD

**Issue by LordBurtz** [Heath123/pakkit#72]
After launching pakkit, setting the port to 25565 and connecting I only get in my minecraft instance the error message `Timed out`. 
Pakkit displays `Failed to obtain profile data for USER, does the account own minecraft?`
The USER account indeed does own minecraft, i followed the microsoft login link.
This error persists on multiple minecraft versions.
How can I fix this?

**Comment by LordBurtz** [comment]
```Incoming connection (::ffff:127.0.0.1)
Will attempt to use launcher_profiles.json for online mode login data
Login done
Incoming connection (::ffff:127.0.0.1)
Will attempt to use launcher_profiles.json for online mode login data
Error: Failed to obtain profile data for Fingolf1n, does the account own minecraft?
    at Object.authenticate (/home/fridolin/Downloads/pakkit-linux-x64/resources/app/node_modules/minecraft-protocol/src/client/microsoftAuth.js:26:40)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Failed to obtain profile data for Fingolf1n, does the account own minecraft?
    at Object.authenticate (/home/fridolin/Downloads/pakkit-linux-x64/resources/app/node_modules/minecraft-protocol/src/client/microsoftAuth.js:26:40)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(node:20203) UnhandledPromiseRejectionWarning: Error: Failed to obtain profile data for Fingolf1n, does the account own minecraft?
    at Object.authenticate (/home/fridolin/Downloads/pakkit-linux-x64/resources/app/node_modules/minecraft-protocol/src/client/microsoftAuth.js:26:40)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(node:20203) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)```
console output

**Comment by LordBurtz** [comment]
nvm  occurred because of misuse.. I looped the proxy back to itself.. I guess that'll break it
