### ISSUE TITLE
Trying to start a 1.19 proxy throws an error

### ISSUE THREAD

**Issue by NoahvdAa** [Heath123/pakkit#75]
When trying to create a proxy with the version set to 1.19(.0), the following error is thrown and the proxy doesn't start:
```
TypeError: Cannot read properties of null (reading 'protocol')
    at Object.exports.startProxy (/Applications/pakkit.app/Contents/Resources/app/src/proxy/java/proxy.js:53:29)
    at startProxy (/Applications/pakkit.app/Contents/Resources/app/src/index.js:230:11)
    at IpcMainImpl.<anonymous> (/Applications/pakkit.app/Contents/Resources/app/src/index.js:212:5)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:161:9959)
    at Object.emit (node:events:394:28)
TypeError: Cannot read properties of null (reading 'protocol')
    at Object.exports.startProxy (/Applications/pakkit.app/Contents/Resources/app/src/proxy/java/proxy.js:53:29)
    at startProxy (/Applications/pakkit.app/Contents/Resources/app/src/index.js:230:11)
    at IpcMainImpl.<anonymous> (/Applications/pakkit.app/Contents/Resources/app/src/index.js:212:5)
    at IpcMainImpl.emit (node:events:394:28)
    at Object.<anonymous> (node:electron/js2c/browser_init:161:9959)
    at Object.emit (node:events:394:28)
```

This error does not happen with 1.18.2.

**Comment by DarkGamerYT** [comment]
**minecraft-data** package needs to be updated because the version used **2.80.0** doesn't support 1.19

**Comment by Remynfv** [comment]
I also ran into this issue, so it seems it's not fixed yet.

**Comment by Mr-EmPee** [comment]
It seems working, just make sure to update the package minecraft data 
- npm install minecraft-data@3.15.3
then use a 1.19 server (1.19.2 isn't the same thing!)

**Comment by Heath123** [comment]
> It seems working, just make sure to update minecraft data run: npm install minecraft-data@3.15.3
> 
> then use a 1.19 server (1.19.2 isn't the same thing!)

This was the solution, my issue before was that I didn't specify the version and the new major version meant it didn't auto update to it

**Comment by Heath123** [comment]
Fixed in https://github.com/Heath123/pakkit/commit/9698706b17252215d74ea3446104ee4839d2d888
